force-app/main/default/objects/Country_Name_Dial_code__mdt/Country_Name_Dial_code__mdt.object-meta.xml
<CustomObject>
    <label>Country Name Dial code</label>
    <pluralLabel>Country Name Dial codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_Name_Dial_code__mdt/fields/code__c.field-meta.xml
<CustomField>
    <fullName>code__c</fullName>
    <label>code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Name_Dial_code__mdt/fields/CountryDialcode__c.field-meta.xml
<CustomField>
    <fullName>CountryDialcode__c</fullName>
    <label>CountryDialcode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/snp_address_form_dialNumbers.cls
public class snp_address_form_dialNumbers {
    @AuraEnabled
    public static Decimal countryDialCode(string countrylabel){
        Decimal data= [SELECT Id, Label, code__c, CountryDialcode__c FROM Country_Name_Dial_code__mdt where label =: countrylabel ].CountryDialcode__c;
        system.debug('data=>>'+data);
   return data;
        
    }
@Auraenabled
    Public static void pointaddress(string fname,string lname,string addresstype,
                                    boolean isdefault,string country,string city,
                                   string state,string postalcode,string phonenum,string companyname,string address,string userId)
    {
   id userdetails =[select AccountId,DefaultCurrencyISOCode,CurrencyISOCode from USER where Id =: userId].AccountId;
         system.debug('accId'+userdetails);                                     
       ContactPointAddress con = new ContactPointAddress();
        con.AddressFirstName=fname;
        con.AddressLastName=lname;
        con.Name= fname +''+ lname;                               
        con.AddressType=addresstype;
        con.ParentId=userdetails;
       con.IsDefault=isdefault;
        con.Country=country;
        con.City=city;
        if(state != '--None--'){
           con.State=state; 
        }
        con.PostalCode=postalcode;
        con.PhoneNumber=phonenum;
        con.CompanyName=companyname;
        con.Street=address;
        insert con;
        system.debug(con);                             

    }

}